#test
import = ["/home/w/.config/alacritty/catppuccin-mocha-dark.toml"]
#import = ["/home/w/.config/alacritty/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Bold"
